'use strict';
/* GENERATED by tools/design/build-palette.js — do not hand-edit.
   Audited by tools/design/cvd-check.js. Mirrored into app/css/tokens.css. */
module.exports = {
  "light": {
    "paper": "#F8F5F0",
    "ink": "#241F19",
    "sea": "#BCD8EB",
    "fills": {
      "never-british": "#EEE9DE",
      "lost-former": "#BBB6B1",
      "dominion": "#FDC3B9",
      "settlement": "#CF786F",
      "crown-conquered": "#AE3D35",
      "company-rule": "#DAAF64",
      "lease": "#61A093",
      "protectorate": "#5583B0",
      "mandate": "#694479",
      "occupied": "#493A2F"
    },
    "hover": {
      "never-british": "#E2DBCA",
      "lost-former": "#B2A99F",
      "dominion": "#FAB0A4",
      "settlement": "#EC7B71",
      "crown-conquered": "#AF0D14",
      "company-rule": "#D59E33",
      "lease": "#3D9786",
      "protectorate": "#3977B0",
      "mandate": "#7B4990",
      "occupied": "#594432"
    },
    "selected": {
      "never-british": "#D6CCB4",
      "lost-former": "#A79A8B",
      "dominion": "#F49C8E",
      "settlement": "#FF857A",
      "crown-conquered": "#9C0006",
      "company-rule": "#CA8F00",
      "lease": "#008C79",
      "protectorate": "#0F69AE",
      "mandate": "#8E50A7",
      "occupied": "#6B4E37"
    },
    "stroke": {
      "never-british": "#88847B",
      "lost-former": "#5B5753",
      "dominion": "#91635C",
      "settlement": "#641F1C",
      "crown-conquered": "#FFA99E",
      "company-rule": "#725000",
      "lease": "#014238",
      "protectorate": "#B6DCFF",
      "mandate": "#C39ED3",
      "occupied": "#9F9084"
    },
    "onFill": {
      "never-british": "#14110D",
      "lost-former": "#14110D",
      "dominion": "#14110D",
      "settlement": "#14110D",
      "crown-conquered": "#FBF8F3",
      "company-rule": "#14110D",
      "lease": "#14110D",
      "protectorate": "#14110D",
      "mandate": "#FBF8F3",
      "occupied": "#FBF8F3"
    },
    "texture": {
      "never-british": "plain",
      "lost-former": "hatch-45",
      "dominion": "rule-h",
      "settlement": "stipple",
      "crown-conquered": "plain",
      "company-rule": "cross",
      "lease": "rule-v",
      "protectorate": "hatch-135",
      "mandate": "stipple-coarse",
      "occupied": "hatch-135-dense"
    },
    "tenure": [
      "#F5E6E2",
      "#E6C4BC",
      "#D6A299",
      "#C58177",
      "#B25F57",
      "#9E3C3A",
      "#890C1D"
    ]
  },
  "night": {
    "paper": "#15120E",
    "ink": "#EFE7D7",
    "sea": "#0B1B2A",
    "fills": {
      "never-british": "#27231E",
      "lost-former": "#423F3B",
      "dominion": "#FFC9BF",
      "settlement": "#C57670",
      "crown-conquered": "#B14936",
      "company-rule": "#D6AC60",
      "lease": "#6AA69A",
      "protectorate": "#5587B6",
      "mandate": "#795288",
      "occupied": "#5B4431"
    },
    "hover": {
      "never-british": "#352F25",
      "lost-former": "#534B43",
      "dominion": "#F9B3A7",
      "settlement": "#E47D75",
      "crown-conquered": "#D24831",
      "company-rule": "#CF9929",
      "lease": "#65BAA9",
      "protectorate": "#5297D4",
      "mandate": "#8D59A2",
      "occupied": "#705035"
    },
    "selected": {
      "never-british": "#463D2E",
      "lost-former": "#655A4D",
      "dominion": "#F09D8F",
      "settlement": "#FF857D",
      "crown-conquered": "#F3482C",
      "company-rule": "#BF8700",
      "lease": "#61D0BB",
      "protectorate": "#52A8F4",
      "mandate": "#A463BD",
      "occupied": "#865D39"
    },
    "stroke": {
      "never-british": "#77746E",
      "lost-former": "#989490",
      "dominion": "#936860",
      "settlement": "#5C1E1C",
      "crown-conquered": "#FFB4A4",
      "company-rule": "#704D00",
      "lease": "#0D483E",
      "protectorate": "#002C50",
      "mandate": "#D4ADE4",
      "occupied": "#B39C89"
    },
    "onFill": {
      "never-british": "#F3ECDE",
      "lost-former": "#F3ECDE",
      "dominion": "#0F0C09",
      "settlement": "#0F0C09",
      "crown-conquered": "#F3ECDE",
      "company-rule": "#0F0C09",
      "lease": "#0F0C09",
      "protectorate": "#0F0C09",
      "mandate": "#F3ECDE",
      "occupied": "#F3ECDE"
    },
    "texture": {
      "never-british": "plain",
      "lost-former": "hatch-45",
      "dominion": "rule-h",
      "settlement": "stipple",
      "crown-conquered": "plain",
      "company-rule": "cross",
      "lease": "rule-v",
      "protectorate": "hatch-135",
      "mandate": "stipple-coarse",
      "occupied": "hatch-135-dense"
    },
    "tenure": [
      "#3C2F2C",
      "#5C403A",
      "#7E5149",
      "#A16259",
      "#C6736B",
      "#EB847E",
      "#FFA19D"
    ]
  },
  "DAY": {
    "never-british": [
      0.9344,
      0.0153,
      87.8
    ],
    "lost-former": [
      0.7803,
      0.0096,
      70.5
    ],
    "dominion": [
      0.866,
      0.068,
      29.5
    ],
    "settlement": [
      0.6666,
      0.1106,
      26.6
    ],
    "crown-conquered": [
      0.5196,
      0.1497,
      27.3
    ],
    "company-rule": [
      0.7764,
      0.1056,
      80.2
    ],
    "lease": [
      0.66,
      0.0687,
      178.6
    ],
    "protectorate": [
      0.5971,
      0.0853,
      248.7
    ],
    "mandate": [
      0.4513,
      0.0937,
      315.2
    ],
    "occupied": [
      0.362,
      0.0283,
      60.1
    ]
  },
  "NIGHT": {
    "never-british": [
      0.2596,
      0.0107,
      81.6
    ],
    "lost-former": [
      0.3685,
      0.0086,
      68
    ],
    "dominion": [
      0.8798,
      0.0638,
      30
    ],
    "settlement": [
      0.6511,
      0.1005,
      25.5
    ],
    "crown-conquered": [
      0.5399,
      0.1407,
      31.9
    ],
    "company-rule": [
      0.7673,
      0.1065,
      80.6
    ],
    "lease": [
      0.6812,
      0.0663,
      179.4
    ],
    "protectorate": [
      0.6073,
      0.0899,
      247.7
    ],
    "mandate": [
      0.501,
      0.0956,
      315.9
    ],
    "occupied": [
      0.4074,
      0.0433,
      60.6
    ]
  },
  "TEXTURE": {
    "never-british": "plain",
    "lost-former": "hatch-45",
    "dominion": "rule-h",
    "settlement": "stipple",
    "crown-conquered": "plain",
    "company-rule": "cross",
    "lease": "rule-v",
    "protectorate": "hatch-135",
    "mandate": "stipple-coarse",
    "occupied": "hatch-135-dense"
  }
};
